const ApiTypes ={
    API_REQUEST:"API_REQUEST",
    API_RESPONSE:"API_RESPONSE",
    POST_REQUEST:"POST_REQUEST",
    POST_RESPONSE:"POST_RESPONSE",
    DELETE_REQUEST:"DELETE_REQUEST",
    DELETE_RESPONSE:"DELETE_RESPONSE",
}
export {ApiTypes};